apiVersion: kubepack.com/v1alpha1
kind: Order
metadata:
  creationTimestamp: "2020-02-26T10:30:56Z"
  name: kubedb-community
  uid: 3ce1ca99-a204-40cf-aec9-4529a840ed78
spec:
  items:
  - chart:
      bundle:
        name: kubedb-community
        version: v0.13.0-rc.0
        sourceRef:
          apiGroup: charts.x-helm.dev
          kind: Legacy
          name: https://bundles.kubepack.com
      name: kubedb
      sourceRef:
        apiGroup: charts.x-helm.dev
        kind: Legacy
        name: https://charts.appscode.com/stable/
      namespace: kube-system
      releaseName: kubedb
      version: v0.13.0-rc.0
  - chart:
      bundle:
        name: kubedb-community
        version: v0.13.0-rc.0
        sourceRef:
          apiGroup: charts.x-helm.dev
          kind: Legacy
          name: https://bundles.kubepack.com
      name: kubedb-catalog
      sourceRef:
        apiGroup: charts.x-helm.dev
        kind: Legacy
        name: https://charts.appscode.com/stable/
      namespace: kube-system
      releaseName: kubedb-catalog
      version: v0.13.0-rc.0
status: {}
