/*
Copyright The Kubepack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubepack.dev/kubepack/apis/kubepack/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PackLister helps list Packs.
type PackLister interface {
	// List lists all Packs in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.Pack, err error)
	// Get retrieves the Pack from the index for a given name.
	Get(name string) (*v1alpha1.Pack, error)
	PackListerExpansion
}

// packLister implements the PackLister interface.
type packLister struct {
	indexer cache.Indexer
}

// NewPackLister returns a new PackLister.
func NewPackLister(indexer cache.Indexer) PackLister {
	return &packLister{indexer: indexer}
}

// List lists all Packs in the indexer.
func (s *packLister) List(selector labels.Selector) (ret []*v1alpha1.Pack, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Pack))
	})
	return ret, err
}

// Get retrieves the Pack from the index for a given name.
func (s *packLister) Get(name string) (*v1alpha1.Pack, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("pack"), name)
	}
	return obj.(*v1alpha1.Pack), nil
}
