/*
Copyright The Kubepack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubepack.dev/kubepack/apis/kubepack/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ProductLister helps list Products.
type ProductLister interface {
	// List lists all Products in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.Product, err error)
	// Get retrieves the Product from the index for a given name.
	Get(name string) (*v1alpha1.Product, error)
	ProductListerExpansion
}

// productLister implements the ProductLister interface.
type productLister struct {
	indexer cache.Indexer
}

// NewProductLister returns a new ProductLister.
func NewProductLister(indexer cache.Indexer) ProductLister {
	return &productLister{indexer: indexer}
}

// List lists all Products in the indexer.
func (s *productLister) List(selector labels.Selector) (ret []*v1alpha1.Product, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Product))
	})
	return ret, err
}

// Get retrieves the Product from the index for a given name.
func (s *productLister) Get(name string) (*v1alpha1.Product, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("product"), name)
	}
	return obj.(*v1alpha1.Product), nil
}
